### ISSUE TITLE
Bad username read from stdin

### ISSUE THREAD

**Issue by Lundbrik** [SimonPersson/spotifyd#13]
When reading credentials from stdin, the username has a newline char from <getline()>, so login will fail.

**Comment by SimonPersson** [comment]
What makes you think that? The username is run through the `trim_whitespace()` function, that one is supposed to remove the newline char. Also, I have tested this. It works for me.

Now, do you actually have a problem or did you just read the code and assumed that something was wrong?

**Comment by Lundbrik** [comment]
I did both, and neither the password or the username is trimmed if it read from stdin, seen here: https://github.com/SimonPersson/spotifyd/blob/master/src/config.c#L148
But it seems that `getpass()` does not keep the delimiter

**Comment by SimonPersson** [comment]
Aha! Will patch that then.

It still works for me though, so I suppose it is trimmed in libspotify too. You can't log in at all? Do you get any error messages?

**Comment by Lundbrik** [comment]
I can login using the config to set username and password, but when I try with stdin, i simply get 'Couldn't log in: Bad username and/or password'. Otherwise I have had no problems, it's a nice little daemon :)

**Comment by SimonPersson** [comment]
I have pushed a commit that is supposed to trim trailing whitespace from usernames now. Try it out!

**Comment by Lundbrik** [comment]
It works, good job :)

**Comment by SimonPersson** [comment]
Great! It's funny that it works for me. Otherwise I would have noticed this bug myself. Whatever, I'm glad it is solved. :)
