### ISSUE TITLE
Close alsa device if no song is playing

### ISSUE THREAD

**Issue by Paspartout** [SimonPersson/spotifyd#16]
Once you start playing some music using spotifyd and then stop the music by either pausing the playback or clearing the playlist it seems that the alsa device connection remains opened.

Because of that I have to for example restart spotifyd when I wake my device up from standby or
kill it for some applications that access /dev/snd directly(in my case forwarding alsa for docker containers).

I don't know if it's best practice or not but I think it would be appropriate for a daemon to close the
the alsa device when no song is currently playing.

As I am learning c at the moment I might be able to fix that issue myself very soon and open a pull request. What do you think about that issue?

**Comment by SimonPersson** [comment]
Perhaps you could investigate how MPD handles this?

If MPD closes the alsa device I'd very much like a pull request!

**Comment by Paspartout** [comment]
Just tested it and MPD seems to close the device when no song is played.

Expect a pull request soon :)

**Comment by SimonPersson** [comment]
Thank you for your investigation! I look forward to the pull request :)
