### ISSUE TITLE
Floating point exception (core dumped)

### ISSUE THREAD

**Issue by jonlorusso** [SimonPersson/spotifyd#2]
When I do this:

    $ sc QADDPL 5
    Added playlist "iTunes" to queue.

I get this:

    Floating point exception (core dumped)

**Comment by SimonPersson** [comment]
And you can reproduce this error multiple times? Would you mind helping me debug this error?

To have a reasonable shot at solving the error, I must have a backtrace. To create a backtrace, follow these steps:
* Edit `Makefile`, append `-g` to the `CFLAGS` line.
* Rebuild the program with `make clean && make`.
* Run spotifyd in GDB `gdb ./spotifyd`
   * If GDB is not installed on your computer, install it through your package manager.
* In GDB, type `run`
* Do what you normally do to make the application crash.
* When it has crashed, type `bt` in the GDB shell.
* Come back with the results.

Ask me if you get stuck with any of these steps.
