### ISSUE TITLE
Couldn't log in.

### ISSUE THREAD

**Issue by lezed1** [SimonPersson/spotifyd#3]
I've installed spotifyd on both Ubuntu and Arch, and tried a Facebook connected Spotify account (both Facebook credentials and Spotify device credentials) and a non Facebook connected Spotify account. After trying both the .rc file and manually entering credentials when running I always get the same output:

    $ spotifyd
    Username: lezed1
    Password: 
    Logged in!
    *There is a pause here*
    Couldn't log in.

Also, I am being logged in as I can see a "new account activity" on Facebook each time I try to use spotifyd.

I'm not sure how to give useful debug output (is there a flag?), so just tell me any commands from which you want the output.

**Comment by saevarb** [comment]
I, too, use Facebook log-in and just installed spotifyd. I had to resort to using Spotify device password to be able to log in, but before that, I also got the "Logged in!" message followed by "Couldn't log in." when it failed initially.

**Comment by SimonPersson** [comment]
I have updated the error reporting during log in now. Pull the code and build again, you should get a much better error message now.

Do you have a premium account? I just added that requirement to the README, that could be the reason.

**Comment by lezed1** [comment]
I do not have a premium account, so that could account for the problem!
