### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [SimonPersson/spotifyd#4]
I have looked at a few source files for your current software. I have noticed that some checks for return codes are missing.

Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [read_config](https://github.com/SimonPersson/spotifyd/blob/69a1cf7231cf60fddc52f6e5ea58488dba671bd4/src/config.c#L74 "Read the system configuration.")
- [pthread_mutex_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialize a mutex.") ⇒ [main](https://github.com/SimonPersson/spotifyd/blob/3135d6f6f2a3be17bfc61266f93cbda0c03cab9a/src/spotifyd.c#L40 "Main function")

**Comment by SimonPersson** [comment]
That should definitely be fixed. I suppose I overlooked checks on `malloc` and `pthread_mutex_init` (and probably plenty of other possible errors :)). We can at least crash more gracefully with an error message explaining the situation. Would you like to send a PR or should I fix it?

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.

Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by SimonPersson** [comment]
I agree, the code should most definitely check for errors. It's not pretty having your program terminate upon a failed malloc (very unlikely, but whatever).

Not really no. But perhaps you can convince me! Myself, I quite like the way errors are handled in most C programs. A function call that can fail is immediately followed by a check and code to handle the error. To me, this reads very well and makes it easy to follow a programs execution. If you have some good examples on how treating error handling as a reusable aspect could look and what benefits it would provide, I'm listening.

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2FC.2B.2B "Tools for static code analysis") also for your software?

Do you find information sources like the following useful?
* Article "[A Reusable Aspect for Memory Allocation Checking](http://aspectc.net/ac_tutorial.html#reusablemachecking "AspectC Tutorial")"
* Document "[Aspect-Oriented Software Development - An Introduction](http://www.info.ucl.ac.be/~jbrichau/courses/introductionToAOSD.pdf "AOSD")" by Johan Brichau and Theo D'Hondt
* Paper "[On Typesafe Aspect Implementations in C++](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.125.2164 "AspectC++")" by Daniel Lohmann and Olaf Spinczyk

**Comment by SimonPersson** [comment]
I tried to build splint but it didn't compile. Then I gave up.

I read the article. While I see the point, I don't agree with it. How is that any better? With code like that no one will understand what happens except for you and me. Error checking immediately after malloc is really clear and can be understood by everyone. It is simple.

As I have fixed the errors you pointed out, I consider this issue closed now.

**Comment by elfring** [comment]
There are more update candidates left over.

Examples:
* atexit
* pthread_create
* pthread_mutex_lock

Further thoughts:
* Would you like to reuse dedicated software tools which can reduce the probability to overlook open issues?
* How do you think about to minimise (manual) programming efforts because of repeated checks you introduced a moment ago?

**Comment by SimonPersson** [comment]
I'm aware, but what do you expect the program to do in those cases? If `atexit` fails, should the program end? That seems unreasonable as the program will work just fine anyways. If `pthread_create` fails, should the program end or should it just keep on playing music? It just doesn't seem reasonable to handle errors that:
* Can't be handled reasonably.
* Most probably wont happen at all.
* Won't cause any more problems than if they weren't handled (provided that if `pthread_mutex_lock` fails the memory is already corrupted somehow, which seems probable).

Yes, I'd love a tool that finds issues in the code, that works on every platform and does not have a ton of dependencies. I have yet to find a good one though.

No, I would not like to reduce the manual effort required to handle errors. As I've explained to you, I prefer to have the error handling visible and clear for the reader.

**Comment by elfring** [comment]
How do you think about descriptions in [an article](http://accu.org/index.php/journals/1706 "Quality Matters #6: Exceptions for Practically-Unrecoverable Conditions") by Matthew Wilson?

**Comment by SimonPersson** [comment]
I think his descriptions are entirely reasonable when developing an application where stability and correctness is of great importance. I don't feel it's is that relevant for this program.
