### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [SimonPersson/spotifyd#5]
I suggest to reuse a higher level build system than [your current small make file](https://github.com/SimonPersson/spotifyd/blob/062174244291303e84f37652bd2ff1e4c7775134/Makefile#L1 "Update candidate") so that powerful checks for software features will become easier.
* [CMake](http://cmake.org/ "CMake build system")
* [Autotools](http://www.gnu.org/software/autoconf/#TOCintroduction "GNU build system")

**Comment by SimonPersson** [comment]
Could you explain the benefits of a more advanced build system?

I'm not all opposed to the idea, I just don't see the point. The way I see it, this software will only realistically compile on GNU/Linux anyways and I figured these more sophisticated build systems would mostly help when you have more possible configurations.

**Comment by elfring** [comment]
* Does [a tool like "autoscan"](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/autoscan-Invocation.html "Using autoscan to create configure.ac") show any software dependencies that you find worth for further considerations?
* How do you think about to support more development environments by [the reuse of build system generators](http://www.cmake.org/cmake/help/v3.1/manual/cmake-generators.7.html#introduction "Selection for build tool generators")?

**Comment by SimonPersson** [comment]
I think you missed my point.

I'm well aware of the benefits a more sophisticated build system can add to a project in general. However, this project will only work on a modern installation of GNU/Linux with a modern glibc anyways. Any such system will have GNU Make installed, don't you think? The way I see it, by using a more sophisticated build system you might actually be limiting the potential amount of users as everyone will have GNU Make installed but not all will have CMake, for example.

**Comment by elfring** [comment]
I suggest to increase the portability for your software application with higher level build tools.

**Comment by SimonPersson** [comment]
I understand, but the dependencies on libspotify and alsa already makes the software limited to linux. A higher level build tool won't help at all with portability as far as I can tell.

**Comment by SimonPersson** [comment]
I'll close this issue now. I'm sticking to GNU Make for now as there are no real benefits to switch right now as far as I can see.
