### ISSUE TITLE
qlist always lists queue from 0 position. 

### ISSUE THREAD

**Issue by saevarb** [SimonPersson/spotifyd#6]
This may or may not be a bug, but it is definitely an inconvenience. `qlist` always lists the queue from the first song that was ever in the queue. The official spotify client doesn't do this -- the next song in the queue is the first one in the list.

This is inconvenient if you have a really long queue. I am working on a wrapper using `dmenu` to select songs from the queue, and this means I can't simply use `head` to display the next 10 songs. I can still work around this using `sc qlist | grep -A 10 "$(sc cur_playing)"`, however.

FWIW, it looks like the fix is as simple as adding `unsigned queue_get_current_position()` to queue.(c|h) and using that inside `command_listq`, as far as I can see.

**Comment by SimonPersson** [comment]
Sounds reasonable. I think I'll add a switch, like the `qrand` one, that will toggle the current behaviour with the one you propose. I suppose that this feature can't be on at the same time as `qrand`, or the `qlist` command will be a bit misleading.

**Comment by saevarb** [comment]
It depends on how you implement the queue. In the official client, the queue reflects the randomness -- that is, you play a playlist, and if you have random on, the queue displays the next song as it was determined by the random order.

IMO, that's the most intuitive way to do it. Fill the queue randomly, then display the randomized order on `qlist`. When `qrand` is toggled off, I guess the queue would have to be reconstructed, probably starting from the song that is currently playing, continuing sequentially. But that won't work for spotifyd if I understand it correctly since it doesn't really just "play a playlist", etc.

**Comment by SimonPersson** [comment]
I see. So then perhaps we could replace the meaning of `qrand` to something like "Reorder the queue randomly". Then we don't have to worry about what happens when `qrand` is turned off as it is not an on/off switch anymore. That's better than the current situation actually as `prev` is broken during random playback today.

**Comment by SimonPersson** [comment]
`qrand` is now changed to mean "Shuffle queue". A new command, `qprint`, toggles the behaviour you're requesting on and off.

I'll close this issue now, thanks for reporting it!
