### ISSUE TITLE
Spotifyd grabs control of audio when it's running

### ISSUE THREAD

**Issue by saevarb** [SimonPersson/spotifyd#8]
It seems that when spotifyd is running, it takes complete control of all sound. On my system, this means(for some reason) that youtube videos don't run at all(not even just on mute) while some videos(like those on facebook) play but without sound. Additionally, playing sound(from a video in chrome, for example) prevents spotifyd from starting properly until it seems to eventually crash with a floating point exception. This may be related to issue #2. 

I am running Arch Linux, and I'm going to take a wild guess that this has something to do with pulseaudio. 

I don't really know much about libalsa, so I'm unsure if this can be fixed without using another library.

**Comment by SimonPersson** [comment]
I'll look into this on a machine running arch. Myself I run Crux and I can't reproduce this error, so pulseaudio seems like a reasonable guess.

Unfortunately I stole the libalsa code from the libspotify documentation, it seems like I will have to look into it after all.
